# config.yaml

# Paths
data_path: "car_price_predictor/dataset/car_prices.csv"
model_save_path: "car_price_predictor/trained/model/car_rent_predictor.pkl"
encoders_path: "car_price_predictor/trained/encoders/"
scaler_path: "car_price_predictor/trained/scaler/"

# Model Parameters
random_state: 42
test_size: 0.2
max_depth: 13
