name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

  download_dataset:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Download dataset from S3
        run: aws s3 cp s3://${{ secrets.S3_DATASET_BUCKET_NAME }}/car_prices.csv car_price_predictor/dataset/car_prices.csv

      - name: Upload dataset as artifact
        uses: actions/upload-artifact@v3
        with:
          name: car-prices-dataset
          path: car_price_predictor/dataset/car_prices.csv

  train_model:
    runs-on: ubuntu-latest
    needs: download_dataset
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

      - name: Download dataset artifact
        uses: actions/download-artifact@v3
        with:
          name: car-prices-dataset
          path: car_price_predictor/dataset/

      - name: Train the model
        run: python train_model.py

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: car_price_predictor/trained/  # Path where the trained model(s) are saved

  run_tests:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

      - name: Download trained model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: car_price_predictor/trained/

      - name: Run tests
        run: pytest tests/ --disable-warnings
        continue-on-error: false  # Fail the job if tests fail

  package_and_upload:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

      - name: Download trained model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: car_price_predictor/trained/

      - name: Create package
        run: python setup.py sdist bdist_wheel  # Create a package using setuptools

      - name: Extract package name and version
        id: extract_version
        run: |
          PACKAGE_NAME=$(python setup.py --name)
          PACKAGE_VERSION=$(python setup.py --version)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package and trained model to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}  # Dynamic S3 bucket name from GitHub Secrets
        run: |
          aws s3 cp dist/ s3://$S3_BUCKET_NAME/packages/$PACKAGE_NAME/$PACKAGE_VERSION/ --recursive
          aws s3 cp car_price_predictor/trained/ s3://$S3_BUCKET_NAME/trained_models/ --recursive
